# Generated by Django 5.0.1 on 2024-02-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_ordermodel_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
