# Generated by Django 5.0.1 on 2024-02-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_ordermodel_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='applied_date',
            field=models.DateTimeField(null=True),
        ),
    ]
